name: BuildTest

on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-cli-v2:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F767ZI]
        profile: [develop]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build-example-application
        run: |
          set -e
          mbed-tools deploy
          mbed-tools compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
