name: BuildTest

on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env
    steps:
      - uses: actions/checkout@v3
      - uses: OUXT-Polaris/build-mbed-app-action@master
        with:
          target_board: NUCLEO_F767ZI
          toolchain: GCC_ARM
