name: BuildTest

on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: wamvtan/firmware_builder:latest
    steps:
      - uses: actions/checkout@v3
      - name: copy files from checkout directory
        run: cp -r /workspace/* /$GITHUB_WORKSPACE/*
      - uses: OUXT-Polaris/build-mbed-app-action@master
        with:
          target_board: NUCLEO_F767ZI
          toolchain: GCC_ARM
      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: cmake_build/NUCLEO_F767ZI/develop/GCC_ARM/*.bin